name: teamcity
services:
  # TeamCity Database
  database:
    image: mysql:9
    container_name: database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
  # TeamCity server
  server:
    image: jetbrains/teamcity-server:2024.07.3
    container_name: server
    ports:
      - "8111:8111"
    volumes:
      - "teamcity_server_data:/data/teamcity_server/datadir"
      - "teamcity_server_logs:/data/teamcity_server/logs"
    depends_on:
      - database
  # TeamCity agent
  agent:
    image: jetbrains/teamcity-agent:2024.07.3
    container_name: agent
    volumes:
      - teamcity_agent_config:/data/teamcity_agent/conf
    environment:
      SERVER_URL: http://server:8111
      AGENT_NAME: teamcity-agent
    depends_on:
      - server

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: ${TEAMCITY_FOLDER}/mysql
      o: bind
  teamcity_server_data:
    driver: local
    driver_opts:
      type: none
      device: ${TEAMCITY_FOLDER}/teamcity-server/data
      o: bind
  teamcity_server_logs:
    driver: local
    driver_opts:
      type: none
      device: ${TEAMCITY_FOLDER}/teamcity-server/logs
      o: bind
  teamcity_agent_config:
    driver: local
    driver_opts:
      type: none
      device: ${TEAMCITY_FOLDER}/teamcity-agent/conf
      o: bind
